config/routes.rb
Rails.application.routes.draw do

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    devise_for :users
    root to: 'homes#top' #全体のトップ画面を/comで表示
    get 'home/about' => 'homes#about'

    resources :users, only: [:index, :show, :edit, :update] do#マイページ
        get :following
        get :followed
    end
    resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do #本の投稿
        resource :favorites, only: [:create, :destroy]
        resources :book_comments, only: [:create, :destroy] #コメント
    end

    get 'relationships/create'
    get 'relationships/destroy'
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
    get '/search' => 'search#search'

end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable

    validates :name, presence: true, length: { minimum: 2, maximum: 20 }
    validates :introduction, length: { maximum: 50 }
    validates :postal_code, presence: true
    validates :prefecture_code, presence: true
    validates :city, presence: true
    validates :street, presence: true

    attachment :profile_image #プロフィール画像投稿ができるようにする

    has_many :books, dependent: :destroy #Bookモデルと1：N
    has_many :book_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォローしている人取得(Userのfollowerから見た関係)
    has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォローされている人取得(Userのfolowedから見た関係)
    has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
    has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人(自分がフォローされている人)

    # ユーザーをフォローする
    def follow(user_id)
        follower.create(followed_id: user_id)
    end

    # ユーザーのフォローを外す
    def unfollow(user_id)
        follower.find_by(followed_id: user_id).destroy
    end

    # フォロー確認をおこなう
    def following?(user)
        following_user.include?(user)
    end

    def favorited_by?(book_id)
        favorites.where(book_id: book_id).exists?
    end

    #JpPrefectureの導入
    include JpPrefecture
    jp_prefecture :prefecture_code

    def prefecture_name
        JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
    end

    def prefecture_name=(prefecture_name)
        self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!
    before_action :ensure_correct_user, only: [:edit, :update] #[]にはURLを打っても行かせない
    
    def index
        @users = User.all
        @book = Book.new
        @user = User.find(current_user.id)
    end

    def show
        @user = User.find(params[:id])
        @book = Book.new
        @books = @user.books #@userにはユーザー情報、そこに紐づいているbooksモデルの本たち
    end

    def edit
        @user = User.find(params[:id])
        if @user == current_user
            render "edit"
        else
            redirect_to user_path(current_user)
        end
    end

    def update
        @user = User.find(params[:id])
        @user.id = current_user.id
        if @user.update(user_params)
            redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
        else
            render "edit"
        end
    end

    def following #フォロワー一覧
        @user = User.find(params[:id])
    end

    def followed #フォロー一覧
        @user = User.find(params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:profile_image, :name, :introduction)
    end

    def ensure_correct_user #[]にはURLを打ったらユーザー詳細に返す
        @user = User.find(params[:id])
        unless @user == current_user
            redirect_to user_path(current_user)
        end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_userinfo.html.erb
<!--User infoの部分テンプレート-->

<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size: '100x100' %>

  <table class="table">
    <tbody>
      <tr>
        <th>name</th> <!--ユーザー名表示-->
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th> <!--自己紹介文-->
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th> <!--フォローしている数-->
        <th><%= link_to "#{user.follower.count}", following_user_path(user) %></th>
      </tr>
      <tr>
        <th>followers</th> <!--フォローされている数-->
        <th><%=link_to "#{user.followed.count}", followed_user_path(user) %></th>
      </tr>
      <tr>
        <th>
          <% unless user == current_user %> <!--自分は表示しない-->
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', unfollow_path(user.id), method: :post, class: "btn btn-info" %>
            <% else %>
              <%= link_to 'フォローする', follow_path(user.id), method: :post, class: "btn btn-success" %>
            <% end %>
          <% end %>
        </th>
    </tbody>
  </table>

  <div class="row"> <!--編集画面へ-->
      <%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_profile" %>
  </div>

app/views/users/edit.html.erb
<!--プロフィール編集画面-->

<div>
  <div class="container">
      <h2>User info</h2>

      <!--サクセスメッセージ-->
      <p id="notice">
        <%= notice %>
      </p>

      <!--エラーメッセージ-->
      <div class="error">
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>

      <!--プロフィール編集フォーム-->
      <%= form_with model:@user, local:true do |f| %>
        <div class="field row">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
        <div class="field row">
          <%= f.label :image %>
          <%= f.attachment_field :profile_image, placeholder: "Image", class: "user-edit-form" %>
        </div>
        <div class="field row">
          <%= f.label :introduction %>
          <%= f.text_area :introduction %>
        </div>
        <div class="actions row">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      <% end %>


  </div>
</div>

app/views/users/followed.html.erb
<!--フォロワー一覧-->

<div class="body">
  <div class="container">
    <div class="row">

      <h1>Follower Users</h1>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
          </tr>
        </thead>

        <tbody>
          <% @user.follower_user.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
              </td>
              <td><%= user.name %></td>
              <% "id: #{user.id}" %>
              <td><%= "フォロー数: #{user.follower.count}" %></td>
              <td><%= "フォロワー数: #{user.followed.count}" %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>
</div>

app/views/users/following.html.erb
<!--フォロー一覧-->

<div class="body">
  <div class="container">
    <div class="row">

      <h1>Follow Users</h1>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
          </tr>
        </thead>

        <tbody>
          <% @user.following_user.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
              </td>
              <td><%= user.name %></td>
              <% "id: #{user.id}" %>
              <td><%= "フォロー数: #{user.follower.count}" %></td>
              <td><%= "フォロワー数: #{user.followed.count}" %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!--ユーザー一覧表示-->

<div class="body">
  <div class="container">

    <!--エラーメッセージ-->
    <div class="error_messege">
      <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>

    <!--サイドバー-->
    <div class="row">
      <div class="col-xs-3">
        <%= render 'users/userinfo', user: @user %> <!--User infoの部分テンプレート-->
        <%= render 'books/newbook', book: @book %> <!--New bookの部分テンプレート-->
      </div>

      <!--ユーザー一覧-->
      <div class="col-xs-9">
        <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th><!--show--></th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
              </td>
              <td><%= user.name %></td>

              <!--フォロー機能-->
              <% "id: #{user.id}" %>
              <td><%= "フォロー数: #{user.follower.count}" %></td>
              <td><%= "フォロワー数: #{user.followed.count}" %></td>

              <% unless user == current_user %> <!--自分は表示しない-->
                <% if current_user.following?(user) %>
                  <td><%= link_to 'フォロー外す', unfollow_path(user.id), method: :post %></td>
                <% else %>
                  <td><%= link_to 'フォローする', follow_path(user.id), method: :post %></td>
                <% end %>
              <% end %>

              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<!--新規登録・ログイン後に表示されるマイページ画面-->

<div class="body">
  <div class="container">

    <!--サクセスメッセージ-->
    <p id="notice">
      <%= notice %>
    </p>

    <!--サイドバー-->
    <div class="row">
      <div class="col-xs-3">
        <%= render 'users/userinfo', user: @user %> <!--User infoの部分テンプレート-->
        <%= render 'books/newbook', book: @book %> <!--New bookの部分テンプレート-->
      </div>

      <!--自分の投稿一覧-->
      <div class="col-xs-9">

        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th><!--ProfileImage--></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                    <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book) %></td> <!--book_path(詳細表示)で(|book|)の投稿(.id)を持ってくる-->
                <td><%= book.body %></td>
                <td>コメント数：<%= book.book_comments.count %></td> <!--each文で使えるのは|book|-->
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>