config/routes.rb
Rails.application.routes.draw do

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    devise_for :users
    root to: 'homes#top' #全体のトップ画面を/comで表示
    get 'home/about' => 'homes#about'

    resources :users, only: [:index, :show, :edit, :update] do#マイページ
        get :following
        get :followed
    end
    resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do #本の投稿
        resource :favorites, only: [:create, :destroy]
        resources :book_comments, only: [:create, :destroy] #コメント
    end

    get 'relationships/create'
    get 'relationships/destroy'
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
    get '/search' => 'search#search'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-inverse">
      <div class="container">
      	<nav class="nav navbar-nav nabvbar-left">
      		<span>Bookers</span>
      	</nav>

        <nav>
      	  <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to " Home", user_path(current_user), class: "glyphicon glyphicon-home" %>
              </li>
              <li class="nav-item">
                <%= link_to " Users", users_path, class: "glyphicon glyphicon-user" %>
              </li>
              <li class="nav-item">
                <%= link_to " Books", books_path, class: "glyphicon glyphicon-book" %>
              </li>
              <li class="nav-item">
                <%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %>
              </li>

            <% else %>
              <li class="nav-item">
                <%= link_to " Home",root_path, class: "glyphicon glyphicon-home" %>
              </li>
              <li class="nav-item">
                <%= link_to " About", home_about_path, class: "glyphicon glyphicon-link" %>
              </li>
              <li class="nav-item">
                <%= link_to " Sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
              </li>
              <li class="nav-item">
                <%= link_to " login", user_session_path, class: "glyphicon glyphicon-log-in" %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <!--検索窓の部分テンプレート-->
    <div class="search-box">
      <% if user_signed_in? %>
        <%= render 'search/search', model: @model, content: @content, method: @method %>
      <% end %>
    </div>

    <%= yield %>
  </body>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">CopyRight Infratop.inc</div>
      </div>
    </div>
  </footer>

</html>